### ISSUE TITLE
[Bug]: cannot start up server while in development environment

### ISSUE THREAD

**Issue by dberardo-com** [odoo/o-spreadsheet#2186] opened 2023-03-08 08:06 UTC
node version: 16.0.0
OS: windows

steps to reproduce:
* npm install
* npm run dev

the live demo correctly starts on port 8080, but the server shuts down due to an error:

```
npm run dev

> @odoo/o-spreadsheet@16.2.0-alpha.3 dev
> npm-run-all build --parallel server serve-static watch:*


> @odoo/o-spreadsheet@16.2.0-alpha.3 build
> npm-run-all build:js bundle:js "bundle:xml -- --outDir build"


> @odoo/o-spreadsheet@16.2.0-alpha.3 build:js
> tsc --module es6 --incremental


> @odoo/o-spreadsheet@16.2.0-alpha.3 bundle:js
> rollup -c -m --configDev


build/js/index.js → build/o_spreadsheet.js...
created build/o_spreadsheet.js in 4.4s

> @odoo/o-spreadsheet@16.2.0-alpha.3 bundle:xml
> node tools/bundle_xml/main.js "--outDir" "build"

Building xml template bundle in "build/" ...done

> @odoo/o-spreadsheet@16.2.0-alpha.3 server
> node tools/server/main.js


> @odoo/o-spreadsheet@16.2.0-alpha.3 watch:ts
> npm run build:js -- --watch


> @odoo/o-spreadsheet@16.2.0-alpha.3 watch:bundle
> npm run bundle:js -- --watch


> @odoo/o-spreadsheet@16.2.0-alpha.3 serve-static
> live-server --open=demo --watch=build/o_spreadsheet.js,build/o_spreadsheet.xml,demo


> @odoo/o-spreadsheet@16.2.0-alpha.3 watch:xml
> node tools/bundle_xml/watch_xml_templates.js

rollup v2.64.0
bundles build/js/index.js → build\o_spreadsheet.js...
[9:04:33 AM]: Connection: 0 messages have been sent
[9:04:33 AM]: Connection: 0 messages have been sent
[9:04:33 AM]: writing 0 messages to ./logs/session.json
ERROR: "server" exited with 1.
```

**Comment by rrahir** [comment] 2023-03-08 09:04
We apparently lack some logs to explain that issue. Most likely, you have run `npm run dev` twice and the first process has not been killed properly. Could you check that you don't have any node process going on  on port `9090` which is the port of the websocket server that handles the collaborative edition.

How to: 
Open Powershell and enter 
```powershell
Get-NetTCPConnection -LocalPort 9090,8080   | select OwningProcess
```
which should yield something like 
![image](https://user-images.githubusercontent.com/10333790/223669397-4817527a-e498-4cc0-9301-6d189e8c7dbd.png)

you can then look for the process with those PIDS and kill them.

Let us know if you still have issues afterwards.

**Comment by rrahir** [comment] 2023-03-08 11:53
Ok,  I do'nt have the time to improve the server script right now but we can quickly explore 2 possibilities:
1. have you been prompted to authorize the use of those ports and agreed to it hen you first started the command ? If not, the ports might be blocked by your own firewall
2. Could you run the following `npm run build` then `npm run serve-static` and try to access `http://127.0.0.1:8080/demo` ? if it succeeds, then the issue is definitely in the websocket server.

**Comment by dberardo-com** [comment] 2023-03-08 13:10
> have you been prompted to authorize the use of those ports and agreed to it hen you first started the command ? If not, the ports might be blocked by your own firewall

no i havent, but usually i have no issue when starting node applications, and i am using the same approach in this instance. I could try to setup a quick logging myself to undertand whats going on. Maybe not today, perhaps later.

> Could you run the following npm run build then npm run serve-static and try to access http://127.0.0.1:8080/demo ? if it succeeds, then the issue is definitely in the websocket server.

will do

**Comment by rrahir** [comment] 2023-03-28 09:26
are you still experiencing that  problem or can we close the issue?

**Comment by dberardo-com** [comment] 2023-11-18 12:56
i have cloned a newer version of the repo and i am not facing this issue anymore ... i would suggest to also report the recommended nodejs version to use for running the project in the README. 

i guess this issue can be closed

**Comment by rrahir** [comment] 2024-01-27 20:47
Thanks for your report, we will update the readme and the documentation, with more furnished examples of extensions!

**Closed by rrahir** 2024-01-27 20:47 UTC
